### ISSUE TITLE
Epynet and wntr errors on Ubuntu 20.04

### ISSUE THREAD

**Issue by gomitolof** [Critical-Infrastructure-Systems-Lab/DHALSIM#40]
I am trying to execute dhalsim on Ubuntu 20.04.6 (just installed, updated and upgraded), but I have always the following errors when running anytown and ky3 examples :

![anytown](https://user-images.githubusercontent.com/52166087/235377772-b05f85e7-966b-4f00-89d7-061f8697ebf5.png)

In general, the first error is obtained when the simulator is wntr, while the second one is obtained when it is epynet.
I tried to install past versions of dhalsim (that were committed at the end of June of the past year), even on Ubuntu 20.04.4, and I had the same errors.

**Comment by gomitolof** [comment]
Hi, using the dev branch, dhalsim works on Ubuntu 20.04.6, so really thanks!

Just as information: some warnings appears during the execution of a topology using epynet simulator. While for wntr simulator the error shown in the previous screen happens even now, but differently from that error, the iterations are performed entirely because it require more time to end the execution.

**Comment by afmurillo** [comment]
Thank you, could you put a screenshot of those warnings here with Ubuntu 20.04.06?
