### ISSUE TITLE
pcap dump from r0

### ISSUE THREAD

**Issue by FedezT** [Critical-Infrastructure-Systems-Lab/DHALSIM#43]
Hello,

I was wondering if there is a way to collect the pcap also from the r0 router in a complex topology ([the router at the higher level](https://github.com/Critical-Infrastructure-Systems-Lab/DHALSIM/blob/master/doc/static/complex_topo_attack.svg)). Currently I can see the dump from all the routers except this one.

Since r0 is the device that routes all the network traffic, it would be interesting to have access to that traffic!

I had a look in the code but I cannot really see where to initialize the tcpdump process for this node.

Thanks a lot!

**Comment by afmurillo** [comment]
Hello,

Although possible to launch a pocess for r0, the problem would be having to launch multiple tcp-dump processes for each of the interfaces available. DHALSIM is already too resource hungry to launch additional process so I won't be adding this feature. I'm sorry. 

If you wish to add it on a forked version, the way to do it would be:

1) Modify automatic_run to launch an "automatic_router" process for r0

  DHALSIM/tree/dev/dhalsim/python2/automatic_run.py
  
  In the method  "automatic_start" you could add some lines after line 108 to do:
  
  node = self.net.get('r0')
  cmd = ["python3", str(automatic_router_path), str(self.intermediate_yaml)), str('r0')]
  self.router_processes.append(node.popen(cmd, stderr=sys.stderr, stdout=sys.stdout))
  
2) Modify the method "start_tcpdump_capture"  to receive an interface name. Modify the "main" method of the same module to launch "start_tcpdump_capture" in a loop for r0

######## Modifying main
    def main(self):
        """
        This function starts the tcp dump and plc process and then waits for the plc
        process to finish.
        """
        if self.router_name == 'r0':
           self.processes_tcp_dump = []
           # It would still require to launch 1 extra process for the SCADA router, probably better to verify before launching that extra    
           # process
           for i, plc in enumerate(self.data["plcs"]):
                interface_name = 'r0-eth' + str(i)
                self.process_tcp_dump.append(self.start_tcpdump_capture(interface_name))
        else: 
            self.process_tcp_dump = self.start_tcpdump_capture(self.interface_name)
        while True:
            pass

######## Modifying start_tcpdump_capture

    def start_tcpdump_capture(self, interface_name):
        """
        Start a tcp dump.
        """
        pcap = self.output_path / (str(interface_name) + '.pcap')

        # Output is not printed to console
        no_output = open(empty_loc, 'w')
        cmd = ['tcpdump', '-i', interface_name, '-w', str(pcap)]
        tcp_dump = subprocess.Popen(cmd, shell=False, stderr=no_output, stdout=no_output)
        return tcp_dump
