### ISSUE TITLE
Does not work on ubuntu 20.04

### ISSUE THREAD

**Issue by GuilleChinarro** [Critical-Infrastructure-Systems-Lab/DHALSIM#46]
I installed ubuntu 22.04 and ran the installation srcipt, after that running any example does not work.

`
Traceback (most recent call last):
  File "/usr/local/bin/dhalsim", line 33, in <module>
    sys.exit(load_entry_point('dhalsim', 'console_scripts', 'dhalsim')())
  File "/home/samfor/DHALSIM/dhalsim/command_line.py", line 86, in main
    runner.run()
  File "/home/samfor/DHALSIM/dhalsim/command_line.py", line 53, in run
    intermediate_yaml_path = config_parser.generate_intermediate_yaml()
  File "/home/samfor/DHALSIM/dhalsim/parser/config_parser.py", line 848, in generate_intermediate_yaml
    yaml_data = InputParser(yaml_data).write()
  File "/home/samfor/DHALSIM/dhalsim/parser/input_parser.py", line 67, in __init__
    self.wn = WaterDistributionNetwork(self.inp_file_path)
  File "/home/samfor/DHALSIM/dhalsim/epynet/network.py", line 17, in __init__
    super().__init__(inputfile=inpfile)
  File "/home/samfor/DHALSIM/dhalsim/epynet/epynet/network.py", line 23, in __init__
    self.ep.ENopen(self.inputfile, self.rptfile, self.binfile)
  File "/home/samfor/DHALSIM/dhalsim/epynet/epynet/epanet2.py", line 84, in ENopen
    raise ENtoolkitError(self, ierr)
dhalsim.epynet.epynet.epanet2.ENtoolkitError: Error 200: one or more errors in input file
`

**Comment by afmurillo** [comment]
Hi, 

Thank you, I think the error is caused because the Mininet branch stopped existing. Could you test again with the dev branch?

**Comment by GuilleChinarro** [comment]
I tried with the dev branch and it worked, however, I got a new error:

cwd dll_path: /usr/local/lib/python3.8/dist-packages/epynet/lib/libepanet.so
ANTLR runtime and generated code versions disagree: 4.13.1!=4.12.0
ANTLR runtime and generated code versions disagree: 4.13.1!=4.12.0
sudo: pkill - f - u: command not found
*** Removing excess controllers/ofprotocols/ofdatapaths/pings/noxes
killall controller ofprotocol ofdatapath ping nox_core lt-nox_core ovs-openflowd ovs-controller ovs-testcontroller udpbwtest mnexec ivs ryu-manager  2> /dev/null
killall -9 controller ofprotocol ofdatapath ping nox_core lt-nox_core ovs-openflowd ovs-controller ovs-testcontroller udpbwtest mnexec ivs ryu-manager  2> /dev/null
pkill -9 -f "sudo mnexec"
*** Removing junk from /tmp
rm -f /tmp/vconn* /tmp/vlogs* /tmp/*.out /tmp/*.log
*** Removing old X11 tunnels
*** Removing excess kernel datapaths
ps ax | egrep -o 'dp[0-9]+' | sed 's/dp/nl:/'
***  Removing OVS datapaths
ovs-vsctl --timeout=1 list-br
ovs-vsctl: unix:/var/run/openvswitch/db.sock: database connection failed (No such file or directory)
ovs-vsctl --timeout=1 list-br
ovs-vsctl: unix:/var/run/openvswitch/db.sock: database connection failed (No such file or directory)
*** Removing all links of the pattern foo-ethX
ip link show | egrep -o '([-_.[:alnum:]]+-eth[[:digit:]]+)'
ip link show
*** Killing stale mininet node processes
pkill -9 -f mininet:
*** Shutting down stale tunnels
pkill -9 -f Tunnel=Ethernet
pkill -9 -f .ssh/mn
rm -f ~/.ssh/mn/*
*** Cleanup complete.
11:19:39 - INFO @ init_database.py: Initializing database.
11:19:39 - DEBUG @ init_database.py:   name  pid  value
0  P78    1      1
1  P79    1      1
2  T41    1  3.051
3  T42    1  3.051
11:19:39 - DEBUG @ init_database.py:    id  time
0   1     0
11:19:39 - DEBUG @ init_database.py:     name  flag
0   PLC1     0
1   PLC2     0
2   PLC3     0
3  scada     0
11:19:39 - DEBUG @ init_database.py: Empty DataFrame
Columns: [name, flag]
Index: []
11:19:39 - DEBUG @ init_database.py: Empty DataFrame
Columns: [name, flag]
Index: []
*** Error setting resource limits. Mininet's performance may be affected.

**Comment by GuilleChinarro** [comment]
> Hi,
> 
> Thank you, I think the error is caused because the Mininet branch stopped existing. Could you test again with the dev branch?

I tried with the dev branch and it worked, however, I got a new error:

```
cwd dll_path: /usr/local/lib/python3.8/dist-packages/epynet/lib/libepanet.so
ANTLR runtime and generated code versions disagree: 4.13.1!=4.12.0
ANTLR runtime and generated code versions disagree: 4.13.1!=4.12.0
sudo: pkill - f - u: command not found
*** Removing excess controllers/ofprotocols/ofdatapaths/pings/noxes
killall controller ofprotocol ofdatapath ping nox_core lt-nox_core ovs-openflowd ovs-controller ovs-testcontroller udpbwtest mnexec ivs ryu-manager  2> /dev/null
killall -9 controller ofprotocol ofdatapath ping nox_core lt-nox_core ovs-openflowd ovs-controller ovs-testcontroller udpbwtest mnexec ivs ryu-manager  2> /dev/null
pkill -9 -f "sudo mnexec"
*** Removing junk from /tmp
rm -f /tmp/vconn* /tmp/vlogs* /tmp/*.out /tmp/*.log
*** Removing old X11 tunnels
*** Removing excess kernel datapaths
ps ax | egrep -o 'dp[0-9]+' | sed 's/dp/nl:/'
***  Removing OVS datapaths
ovs-vsctl --timeout=1 list-br
ovs-vsctl: unix:/var/run/openvswitch/db.sock: database connection failed (No such file or directory)
ovs-vsctl --timeout=1 list-br
ovs-vsctl: unix:/var/run/openvswitch/db.sock: database connection failed (No such file or directory)
*** Removing all links of the pattern foo-ethX
ip link show | egrep -o '([-_.[:alnum:]]+-eth[[:digit:]]+)'
ip link show
*** Killing stale mininet node processes
pkill -9 -f mininet:
*** Shutting down stale tunnels
pkill -9 -f Tunnel=Ethernet
pkill -9 -f .ssh/mn
rm -f ~/.ssh/mn/*
*** Cleanup complete.
11:19:39 - INFO @ init_database.py: Initializing database.
11:19:39 - DEBUG @ init_database.py:   name  pid  value
0  P78    1      1
1  P79    1      1
2  T41    1  3.051
3  T42    1  3.051
11:19:39 - DEBUG @ init_database.py:    id  time
0   1     0
11:19:39 - DEBUG @ init_database.py:     name  flag
0   PLC1     0
1   PLC2     0
2   PLC3     0
3  scada     0
11:19:39 - DEBUG @ init_database.py: Empty DataFrame
Columns: [name, flag]
Index: []
11:19:39 - DEBUG @ init_database.py: Empty DataFrame
Columns: [name, flag]
Index: []
*** Error setting resource limits. Mininet's performance may be affected.
```

**Comment by afmurillo** [comment]
Hello sorry for that,

I just did a push into dev, could you try again? Thank you

**Comment by GuilleChinarro** [comment]
> Hello sorry for that,
> 
> I just did a push into dev, could you try again? Thank you

The first two ANTLR-related errors have disappeared. However the error `*** Error setting resource limits. Mininet's performance may be affected.` persists and the simulation does not progress. Any ideas?

**Comment by afmurillo** [comment]
> > Hello sorry for that,
> > I just did a push into dev, could you try again? Thank you
> 
> The first two ANTLR-related errors have disappeared. However the error `*** Error setting resource limits. Mininet's performance may be affected.` persists and the simulation does not progress. Any ideas?

Which environment are you using to run? I tested today on a virtual machine with Ubuntu 20.04 and I cannot reproduce this error

**Comment by GuilleChinarro** [comment]
> > > Hello sorry for that,
> > > I just did a push into dev, could you try again? Thank you
> > 
> > 
> > The first two ANTLR-related errors have disappeared. However the error `*** Error setting resource limits. Mininet's performance may be affected.` persists and the simulation does not progress. Any ideas?
> 
> Which environment are you using to run? I tested today on a virtual machine with Ubuntu 20.04 and I cannot reproduce this error

I am testing on docker with Ubuntu 20.04

**Comment by afmurillo** [comment]
I haven't tested deployin DHALSIM on docker, but there seems to be a similar entry in StackOverflow regarding an issue similar to this: https://stackoverflow.com/questions/42920605/mininets-cli-get-errorerror-setting-resource-limits-mininets-performance-may

Maybe you could give it a try?

**Comment by GuilleChinarro** [comment]
> Hello,
> 
> Have you had any luck with the suggested fix?

Hi, sorry for the delay, I've been looking for a way to fix it, I'm still working on it, no luck so far.

**Comment by GuilleChinarro** [comment]
Hello, after some time testing I have managed to start a ctown simulation, however this happens on iteration 11. I am using an Ubuntu virtual machine with the dev branch.

`Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/cpppo/server/enip/client.py", line 2248, in <module>
    sys.exit( main() )
  File "/usr/local/lib/python3.10/dist-packages/cpppo/server/enip/client.py", line 2177, in main
    with connector_cls( host=addr[0], port=addr[1], timeout=timeout, profiler=profiler,
  File "/usr/local/lib/python3.10/dist-packages/cpppo/server/enip/client.py", line 1250, in __init__
    super( connector, self ).__init__( host=host, port=port, timeout=timeout, **kwds )
  File "/usr/local/lib/python3.10/dist-packages/cpppo/server/enip/client.py", line 436, in __init__
    self.conn		= socket.create_connection( self.addr, timeout=timeout )
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
TimeoutError: timed out
`

**Comment by afmurillo** [comment]
Hello, thank you and sorry for my late response. Are you trying to run the "ctown_unconstrained_blackbox_concealment_mitm"? (The default ctown configuration file), I am still debugging that attack so I would recommend to comment the line that launches that attack in the experiment, the other attacks should work better
